version: '3.8'
services:
  users:
    build: ./users
    ports:
      - "4000:4000"
  trabajos:
    build: ./trabajos
    ports:
      - "5000:5000"
  equipos:
    build: ./equipos
    ports:
      - "6000:6000"
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - users
      - trabajos
      - equipos