version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
  products-service:
    build: ./products-service
    ports:
      - "5000:5000"
  orders-service:
    build: ./orders-service
    ports:
      - "6000:6000"
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - products-service
      - orders-service
