version: '3.9'
services:
  trabajos:
    build:
      context: ./trabajos
    environment:
      - PORT=7000
      - DATABASE_URL=postgresql://gaspar:armando1gaspar@localhost:5432/trabajos
    ports:
      - "7000:7000"
    networks:
      - backend

  users:
    build:
      context: ./users
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://gaspar:armando1gaspar@localhost:5432/trabajos
    ports:
      - "5000:5000"
    networks:
      - backend

  equipos:
    build:
      context: ./equipos
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://gaspar:armando1gaspar@localhost:5432/trabajos
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
