const express = require('express');
const { getUsers, getUserById, updateUser, deleteUser, getUsersByRole } = require('../controllers/user.controller');
const verifyToken = require('../middlewares/auth.middleware');
const router = express.Router();
router.get('/', verifyToken, getUsers);
router.get('/:id', verifyToken, getUserById);
router.put('/:id', verifyToken, updateUser);
router.delete('/:id', verifyToken, deleteUser);
router.get('/role/:roleId', verifyToken, getUsersByRole);
module.exports = router;
